data:
  distances: [3, 5, 7, 11, 15, 21]
  train_samples_per_distance: 30000
  val_samples_per_distance: 500
  error_rate: 0.1
  train_seed: 42
  val_seed: 123
  use_fast_decoder: false  

model:
  input_dim: 4
  hidden_dim: 256
  num_layers: 21 #32
  dropout: 0.2

training:
  epochs: 400
  batch_size: 16
  lr: 0.001
  patience: 300
